<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>CortanaDesktop</AssemblyName>
        <RootNamespace>CortanaDesktop</RootNamespace>
        <LangVersion>preview</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\CortanaLib\CortanaLib.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="out\**" />
      <EmbeddedResource Remove="out\**" />
      <None Remove="out\**" />
    </ItemGroup>

</Project>
