#!/usr/bin/zsh

if (($# == 1)) then
    if [ "$1" = "--update" ] || [ "$1" = "-u" ]; then
	    git pull . main;
    elif [ "$1" = "--reset" ] || [ "$1" = "-r" ]; then
	    git fetch --all && git reset --hard origin/main;
    elif [ "$1" = "--kill" ] || [ "$1" = "-k" ]; then
	    pkill -SIGKILL CortanaKernel;
	  elif [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
      echo "--update";
    fi
elif (($# == 0)) then
  cd ./Kernel || exit;
  mkdir -p Log
  nohup dotnet run >>Log/Log.log 2>>Log/Error.log & disown;
fi
