#!/usr/bin/zsh
cd ~/Cortana || exit

if (($# == 1)) then
    if [ "$1" = "--update" ] || [ "$1" = "-u" ]; then
	    git fetch --all && git pull;
    elif [ "$1" = "--reset" ] || [ "$1" = "-r" ]; then
        cp -r CortanaKernel/Storage/Config ~/
        yes | rm -rf *
	    git fetch --all && git reset --hard origin/main;
        mv ~/Config ~/Cortana/CortanaKernel/Storage/
    elif [ "$1" = "--kill" ] || [ "$1" = "-k" ]; then
	    killall -qwI dotnet;
        killall -qwI CortanaKernel
        echo "Cortana killed"
	  elif [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
      echo "cortana-run --update -u  git fetch and pull";
      echo "cortana-run --reset -r   git fetch and reset"
      echo "cortana-run --kill -k    kill active process"
      echo "cortana-run              run cortana"
    fi
elif (($# == 0)) then
  cd ./CortanaKernel || exit;
  rm -rf Log
  mkdir Log
  nohup dotnet run >>Log/Log.log 2>>Log/Error.log & disown;
  echo "Cortana booting up..."
fi
