#!/usr/bin/zsh
cd ~/Cortana || exit

if (($# == 1)) then
    if [ "$1" = "--update" ] || [ "$1" = "-u" ]; then
	    git fetch --all && git pull;
    elif [ "$1" = "--reset" ] || [ "$1" = "-r" ]; then
        cp -r Storage/Config ~/
        yes | rm -rf *
	    git fetch --all && git reset --hard origin/main;
        mv ~/Config Storage/
    elif [ "$1" = "--stop" ] || [ "$1" = "-s" ]; then
        killall -s SIGINT --quiet --ignore-case --wait Cortana;
        echo "Cortana stopped"
    elif [ "$1" = "--kill" ] || [ "$1" = "-k" ]; then
        killall --quiet --ignore-case --wait Cortana;
        echo "Cortana killed"
	elif [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
      echo "cortana-run --update -u  git fetch and pull";
      echo "cortana-run --reset -r   git fetch and reset"
      echo "cortana-run --kill -k    try kill active process"
      echo "cortana-run --stop -s    correctly stop process"
      echo "cortana-run              run cortana"
    fi
elif (($# == 0)) then
  rm -rf Storage/Log
  mkdir Storage/Log
  nohup dotnet run --project Bootloader/Bootloader.csproj >>Storage/Log/Log.log 2>>Storage/Log/Error.log & disown;
  echo "Cortana booting up..."
fi
