#!/usr/bin/zsh
cd ~/Cortana || exit;

if (($# == 1))
then
    if [ "$1" = "--update" ] || [ "$1" = "-u" ]
    then
	    git fetch --all && git pull;
    elif [ "$1" = "--start" ] || [ "$1" = "-s" ]
    then
	    rm -rf Storage/Log;
        mkdir Storage/Log;
        nohup dotnet run --project Bootloader/Bootloader.csproj >>Storage/Log/Log.log 2>>Storage/Log/Error.log & disown;
        echo "Cortana booting up...";
    elif [ "$1" = "--restart" ] || [ "$1" = "-r" ]
    then
        cortana --update;
        cortana --kill;
        cortana --start;
    elif [ "$1" = "--force" ] || [ "$1" = "-f" ]
    then
        cp -r Storage/Config ~/
        yes | rm -rf *
	    git fetch --all && git reset --hard origin/main;
        mv ~/Config Storage/
    elif [ "$1" = "--kill" ] || [ "$1" = "-k" ]
    then
        killall -s SIGINT --quiet --ignore-case --wait Cortana;
        echo "Cortana stopped"
	elif [ "$1" = "--help" ] || [ "$1" = "-h" ]
    then
      echo "cortana --update -u   git fetch and pull";
      echo "cortana --force -f    git fetch and reset"
      echo "cortana --kill -k     stop cortana safely"
      echo "cortana --start -s    boot up cortana"
      echo "cortana --restart -r  update and restart"
    fi
elif (($# == 0)); then
    curl --silent -w '\n' cortana-home.ddns.net:8080/api/;
fi
