#!/usr/bin/zsh

mkdir -p ~/.config/Cortana
cd ~/Cortana || exit;
log_folder=~/.config/Cortana/Log;

if (($# == 1))
then
    if [ "$1" = "git" ]
    then
      git fetch --all && git pull;
    elif [ "$1" = "run" ]
    then
      CortanaKernel/out/CortanaKernel >>"$log_folder"/CortanaKernel.log 2>>"$log_folder"/CortanaKernel.log;
    elif [ "$1" = "build" ]
    then
      rm -rf "$log_folder";
      mkdir "$log_folder";
      dotnet build CortanaKernel -o CortanaKernel/out --artifacts-path CortanaKernel/out/lib >>"$log_folder"/CortanaBuild.log 2>>"$log_folder"/CortanaBuild.err;
    elif [ "$1" = "start" ]
    then
      nohup cortana run &>/dev/null & disown;
      echo "Cortana starting";
    elif [ "$1" = "boot" ]
    then
      nohup sh -c "cortana build && cortana start" &>/dev/null & disown;
      echo "Cortana building";
    elif [ "$1" = "restart" ]
    then
      cmd="sleep 5 && cortana start";
      eval "${cmd}" &>/dev/null & disown;
      cortana stop;
    elif [ "$1" = "reboot" ]
    then
      cmd="sleep 5 && cortana boot";
      eval "${cmd}" &>/dev/null & disown;
      cortana stop;
    elif [ "$1" = "update" ]
    then
      cortana git;
	    cortana reboot;
    elif [ "$1" = "reset" ]
    then
        cortana stop;
        rm -rf ./*
	      git fetch --all && git reset --hard origin/main;
	      cortana boot;
    elif [ "$1" = "stop" ]
    then
        killall -s SIGUSR1 --quiet --ignore-case --wait CortanaKernel &>/dev/null;
        echo "Cortana stopped"
    elif [ "$1" = "kill" ]
    then
        killall -s SIGKILL --quiet --ignore-case --wait CortanaKernel &>/dev/null;
        echo "Cortana killed"
	elif [ "$1" = "help" ]
    then
      echo "cortana git             git fetch and pull";
      echo "cortana build           build source only";
      echo "cortana start/restart   start/restart without building";
      echo "cortana boot/reboot     start/restart after building";
      echo "cortana update          update source and reboot";
      echo "cortana reset           force update source";
      echo "cortana stop            stop safely";
      echo "cortana kill            kill process";
    fi
fi
