#!/usr/bin/zsh

if [ "$1" = "log" ]; then
    blue='\033[0;34m';
    echo -e "${blue}$(cortana) ➤  $(cortana raspberry temp)";
else
    api="http://cortana-api.ddns.net:8080";
    url=$(echo "$@" | sed 's! !\/!g')
    curl --silent -w '\n' "$api/${url}";
fi
